### ISSUE TITLE
Bioconductor checklist 1 - Basic Development

### ISSUE THREAD

**Issue by Wangxin555** [Niinleslie/MesKit#14]
- [x]  Update _Bioconductor_ and _R_, see [ devel version of Bioconductor](http://www.bioconductor.org/packages/devel/BiocViews.html#___Software) and [using devel version of Bioconductor](http://www.bioconductor.org/developers/how-to/useDevel/) (choose the option _Using ‘bioc-devel’ during mid-April to mid-October_)

- [x]  Pass _R CMD check_ with **no errors** and **no warnings** using a recent R-devel. Ttry to address all notes that arise during build or check.
- [x]  Pass _R CMD_ [BiocCheck ](https://bioconductor.org/packages/devel/bioc/html/BiocCheck.html) with no errors and no warnings.

- [x]  Filenames are not different only in case, eg. names of "SYSU" and "sysu" are not acceptable.

- [x]  Source package resulting from running _R CMD build_ occupies < 5MB on disk.

- [ ]  The package requires < 10 minutes to run _R CMD check --no-build-vignettes_. Using the --no-build-vignettes option ensures that the vignette is built only once.

- [x]  Vignette and man page examples use <= 3GB of memory.

- [x]  For software packages, individual files <= 5MB. 

- [ ]  Raw package directory not contain unnecessary files, system files, or hidden files such as .DS_Store, .project, .git, cache file, log files, .Rproj, .so, etc.. These files may be present in your local directory but should not be commited to git, see _The .gitignore File_ Part. (in the uncoming checklist)

**Comment by Ninomoriaty** [comment]
> * [ ]   Update _Bioconductor_ and _R_, see [ devel version of Bioconductor](http://www.bioconductor.org/packages/devel/BiocViews.html#___Software) and [using devel version of Bioconductor](http://www.bioconductor.org/developers/how-to/useDevel/) (choose the option _Using ‘bioc-devel’ during mid-April to mid-October_)
> * [ ]   Pass _R CMD check_ with **no errors** and **no warnings** using a recent R-devel. Ttry to address all notes that arise during build or check.
> * [ ]   Pass _R CMD_ [BiocCheck ](https://bioconductor.org/packages/devel/bioc/html/BiocCheck.html) with no errors and no warnings.
> * [ ]   Filenames are not different only in case, eg. names of "SYSU" and "sysu" are not acceptable.
> * [ ]   Source package resulting from running _R CMD build_ occupies < 5MB on disk.
> * [ ]   The package requires < 10 minutes to run _R CMD check --no-build-vignettes_. Using the --no-build-vignettes option ensures that the vignette is built only once.
> * [ ]   Vignette and man page examples use <= 3GB of memory.
> * [ ]   For software packages, individual files <= 5MB.
> * [ ]   Raw package directory not contain unnecessary files, system files, or hidden files such as .DS_Store, .project, .git, cache file, log files, .Rproj, .so, etc.. These files may be present in your local directory but should not be commited to git, see _The .gitignore File_ Part. (in the uncoming checklist)

**Comment by Ninomoriaty** [comment]
sorry for my error.......

**Comment by likelet** [comment]
if the code passes the linting check of bioC. plz tip the checkbox for recording
