### ISSUE TITLE
Bioconductor checklist 2 - Description

### ISSUE THREAD

**Issue by Wangxin555** [Niinleslie/MesKit#15]
- [ ]  “Package:” field: The name of the package. **Be case sensitive, be unique.**. To check whether it is an unique name, run
```
     if (!requireNamespace("BiocManager"))
     install.packages("BiocManager")
     BiocManager::install("MyPackage")
```
- [ ]  “Version:” field: When first submitted to Bioconductor, a package should have pre-release version 0.99.0, see [Version Numbering](https://bioconductor.org/developers/how-to/version-numbering/) 

- [ ]  “Authors@R or Author/Maintainer:” field: Only use _Author@R_ format to give all the authors proper roles. 
If you have ORCID, provide identifier like this:  
_person("Lori", "Shepherd", email=xxx, role=c("cre", aut"), comment = c(ORCID = "0000-0002-5910-4010"))_. About [ORCID](https://orcid.org/) .

- [ ]  “License:” field: Refer to a standard license (see wikipedia) using one of R’s standard specifications. Be specific about any version that applies. Have we gotten the needed **licensing agreements** for packages we are depending on in our package?

- [ ]  “LazyData:” field: Not including _LazyData: TRUE_ if our package includes data.

- [ ]  “Depends/Imports/Suggests/Enhances:” fields: 
1. All packages are available via _Bioconductor_ or _CRAN_.

2. **No duplication** of functionality available in other Bioconductor packages. See [Common Bioconductor Methods and Classes](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/) 

3.  A package can be listed only once between Depends/Imports/Suggests/Enhances. Determaine placement, see [Requirements](http://www.bioconductor.org/developers/package-guidelines/#gitignore) , in DESCRIPTION part, point 8.

- [ ]  “SystemRequirements:” field: This field is for listing any external software which is required, but not automatically installed by the normal package installation process. If the installation process is non-trivial, a top-level README file should be included to document the process.

- [ ]  “biocViews:” field: **REQUIRED!**  Specify at least two [biocViews categories](https://bioconductor.org/packages/release/BiocViews.html) 

- [ ]  “BugReports:” field: Encouraged to add relevant links to Github for reporting Issues.

- [ ]  “URL:” field: Directs users to source code repositories, additional help resources.

- [ ]  "Video:" field: Add instructional videos if we have.

- [ ]  “Collates:” field: This may be necessary to order class and method definitions appropriately during package installation.

**Comment by Niinleslie** [comment]
- [ ]  “Package:” field: The name of the package. **Be case sensitive, be unique.**. To check whether it is an unique name, run
```
     if (!requireNamespace("BiocManager"))
     install.packages("BiocManager")
     BiocManager::install("MyPackage")
```
- [ ]  “Version:” field: When first submitted to Bioconductor, a package should have pre-release version 0.99.0, see [Version Numbering](https://bioconductor.org/developers/how-to/version-numbering/) 

- [ ]  “Authors@R or Author/Maintainer:” field: Only use _Author@R_ format to give all the authors proper roles. 
If you have ORCID, provide identifier like this:  
_person("Lori", "Shepherd", email=xxx, role=c("cre", aut"), comment = c(ORCID = "0000-0002-5910-4010"))_. About [ORCID](https://orcid.org/) .

- [ ]  “License:” field: Refer to a standard license (see wikipedia) using one of R’s standard specifications. Be specific about any version that applies. Have we gotten the needed **licensing agreements** for packages we are depending on in our package?

- [ ]  “LazyData:” field: Not including _LazyData: TRUE_ if our package includes data.

- [ ]  “Depends/Imports/Suggests/Enhances:” fields: 
1. All packages are available via _Bioconductor_ or _CRAN_.

2. **No duplication** of functionality available in other Bioconductor packages. See [Common Bioconductor Methods and Classes](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/) 

3.  A package can be listed only once between Depends/Imports/Suggests/Enhances. Determaine placement, see [Requirements](http://www.bioconductor.org/developers/package-guidelines/#gitignore) , in DESCRIPTION part, point 8.

- [ ]  “SystemRequirements:” field: This field is for listing any external software which is required, but not automatically installed by the normal package installation process. If the installation process is non-trivial, a top-level README file should be included to document the process.

- [ ]  “biocViews:” field: **REQUIRED!**  Specify at least two [biocViews categories](https://bioconductor.org/packages/release/BiocViews.html) 

- [ ]  “BugReports:” field: Encouraged to add relevant links to Github for reporting Issues.

- [ ]  “URL:” field: Directs users to source code repositories, additional help resources.

- [ ]  "Video:" field: Add instructional videos if we have.

- [ ]  “Collates:” field: This may be necessary to order class and method definitions appropriately during package installation.
