### ISSUE TITLE
Bioconductor checklist 3 - Coding Style-1

### ISSUE THREAD

**Issue by Wangxin555** [Niinleslie/MesKit#17]
- [ ]  Indentation
1.  Use 4 spaces for indenting. No tabs
2.  No lines longer than 80 characters

- [x]  Variable names: 
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words

- [x]  Function names
1.  Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words
2.  Do not use ‘.’ 
3.  Prefix non-exported functions with a ‘.’

- [ ]  Class names
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words

- [x]  File names
1.  Filename extension for R code should be ‘.R’
2.  Filename extension for man pages should be ‘.Rd’

- [ ]  Use of space
1.  Always use space after a comma
Like: _a, b, c_
2.  No space around “=” when using named arguments to functions
Like: _somefunc(a=1, b=2)_
3.  Space around all binary operators: 
Like:  _a == b_

- [x]  Comments
1.  Use “##” to start full-line comments
2.  Indent at the same level as surrounding code

- [ ]  End-User messages
1.  _message()_ communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation
2.  _warning()_ communicates unusual situations handled by your code
3.  _stop()_ indicates an error condition
4.  _cat()_ or _print()_ are used only when displaying an object to the user, e.g., in a _show_ method

- [x]  Misc
Use _<-_ not _=_ for assignment

**Comment by Ninomoriaty** [comment]
- [ ]  Indentation
1.  Use 4 spaces for indenting. No tabs
2.  No lines longer than 80 characters

- [ ]  Variable names: 
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words

- [ ]  Function names
1.  Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words
2.  Do not use ‘.’ 
3.  Prefix non-exported functions with a ‘.’

- [ ]  Class names
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words


- [ ]  File names
1.  Filename extension for R code should be ‘.R’
2.  Filename extension for man pages should be ‘.Rd’


- [ ]  Use of space
1.  Always use space after a comma
Like: _a, b, c_
2.  No space around “=” when using named arguments to functions
Like: _somefunc(a=1, b=2)_
3.  Space around all binary operators: 
Like:  _a == b_


- [ ]  Comments
1.  Use “##” to start full-line comments
2.  Indent at the same level as surrounding code


- [ ]  End-User messages
1.  _message()_ communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation
2.  _warning()_ communicates unusual situations handled by your code
3.  _stop()_ indicates an error condition
4.  _cat()_ or _print()_ are used only when displaying an object to the user, e.g., in a _show_ method


- [ ]  Misc
Use _<-_ not _=_ for assignment

**Comment by chenjy327** [comment]
- [x]  Indentation
1.  Use 4 spaces for indenting. No tabs
2.  No lines longer than 80 characters

- [x]  Variable names: 
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words

- [x]  Function names
1.  Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words
2.  Do not use ‘.’ 
3.  Prefix non-exported functions with a ‘.’

- [x]  Class names
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words


- [x]  File names
1.  Filename extension for R code should be ‘.R’
2.  Filename extension for man pages should be ‘.Rd’


- [x]  Use of space
1.  Always use space after a comma
Like: _a, b, c_
2.  No space around “=” when using named arguments to functions
Like: _somefunc(a=1, b=2)_
3.  Space around all binary operators: 
Like:  _a == b_


- [x]  Comments
1.  Use “##” to start full-line comments
2.  Indent at the same level as surrounding code


- [x]  End-User messages
1.  _message()_ communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation
2.  _warning()_ communicates unusual situations handled by your code
3.  _stop()_ indicates an error condition
4.  _cat()_ or _print()_ are used only when displaying an object to the user, e.g., in a _show_ method


- [x]  Misc
Use _<-_ not _=_ for assignment

**Comment by Niinleslie** [comment]
- [ ]  Indentation
1.  Use 4 spaces for indenting. No tabs
2.  No lines longer than 80 characters

- [ ]  Variable names: 
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words

- [ ]  Function names
1.  Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words
2.  Do not use ‘.’ 
3.  Prefix non-exported functions with a ‘.’

- [ ]  Class names
Use [camelCaps](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95/7794053) , initial lowercase, then alternate case between words


- [ ]  File names
1.  Filename extension for R code should be ‘.R’
2.  Filename extension for man pages should be ‘.Rd’


- [ ]  Use of space
1.  Always use space after a comma
Like: _a, b, c_
2.  No space around “=” when using named arguments to functions
Like: _somefunc(a=1, b=2)_
3.  Space around all binary operators: 
Like:  _a == b_


- [ ]  Comments
1.  Use “##” to start full-line comments
2.  Indent at the same level as surrounding code


- [ ]  End-User messages
1.  _message()_ communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation
2.  _warning()_ communicates unusual situations handled by your code
3.  _stop()_ indicates an error condition
4.  _cat()_ or _print()_ are used only when displaying an object to the user, e.g., in a _show_ method


- [ ]  Misc
Use _<-_ not _=_ for assignment
