### ISSUE TITLE
Bioconductor checklist 4 - Coding Style-2

### ISSUE THREAD

**Issue by Wangxin555** [Niinleslie/MesKit#18]
- [ ]  Use _vapply()_ instead of _sapply()_ and use the various apply functions instead of for loops.

- [ ]  Use _seq_len()_ or _seq_along()_ instead of _1:..._

- [x]  Use TRUE/FALSE instead of T/F

- [ ]  Avoid _class()==_ and _class()!=_ instead use _is()_

- [x]  Use _system2()_ instead of _system_

- [x]  Do not use _set.seed_ in any internal R code

- [ ]  No _browser()_ calls should be in code

- [ ]  Avoid the use of <<-

- [ ]  Avoid use of direct slot access with _@_ or _slot()_. Accessor methods should be created and utilized

- [x]  Use _dev.new()_ to start a graphics drive if necessary. Avoid using _x11()_ or _X11()_

- [ ]  Avoid re-implementing functionality or classes

- [ ]  Avoid large chunks of repeated code

- [ ]  Excessively long functions should be avoided. Write small functions

- [ ]  Argument names to functions should be descriptive and well documented

- [ ]  Vectorize! Many R operations are performed on the whole object, not just the elements of the object 
(e.g., _sum(x)_, not _x[1] + x[2] + x[3]_ + ...).

**Comment by Ninomoriaty** [comment]
- [x]  Use _vapply()_ instead of _sapply()_ and use the various apply functions instead of for loops.

- [x]  Use _seq_len()_ or _seq_along()_ instead of _1:..._

- [x]  Use TRUE/FALSE instead of T/F

- [x]  Avoid _class()==_ and _class()!=_ instead use _is()_

- [x]  Use _system2()_ instead of _system_

- [x]  Do not use _set.seed_ in any internal R code

- [x]  No _browser()_ calls should be in code

- [x]  Avoid the use of <<-

- [x]  Avoid use of direct slot access with _@_ or _slot()_. Accessor methods should be created and utilized

- [x]  Use _dev.new()_ to start a graphics drive if necessary. Avoid using _x11()_ or _X11()_

- [x]  Avoid re-implementing functionality or classes

- [x]  Avoid large chunks of repeated code

- [x]  Excessively long functions should be avoided. Write small functions

- [x]  Argument names to functions should be descriptive and well documented

- [x]  Vectorize! Many R operations are performed on the whole object, not just the elements of the object 
(e.g., _sum(x)_, not _x[1] + x[2] + x[3]_ + ...).

**Comment by chenjy327** [comment]
- [x]  Use _vapply()_ instead of _sapply()_ and use the various apply functions instead of for loops.

- [x]  Use _seq_len()_ or _seq_along()_ instead of _1:..._

- [x]  Use TRUE/FALSE instead of T/F

- [x]  Avoid _class()==_ and _class()!=_ instead use _is()_

- [x]  Use _system2()_ instead of _system_

- [x]  Do not use _set.seed_ in any internal R code

- [x]  No _browser()_ calls should be in code

- [x]  Avoid the use of <<-

- [x]  Avoid use of direct slot access with _@_ or _slot()_. Accessor methods should be created and utilized

- [x]  Use _dev.new()_ to start a graphics drive if necessary. Avoid using _x11()_ or _X11()_

- [x]  Avoid re-implementing functionality or classes

- [x]  Avoid large chunks of repeated code

- [x]  Excessively long functions should be avoided. Write small functions

- [x]  Argument names to functions should be descriptive and well documented

- [x]  Vectorize! Many R operations are performed on the whole object, not just the elements of the object 
(e.g., _sum(x)_, not _x[1] + x[2] + x[3]_ + ...).
